// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Trd_GetMaxTrdQtys/Trd_GetMaxTrdQtys.proto

package Trd_GetMaxTrdQtys

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "limgo/futupb/Common"
import Trd_Common "limgo/futupb/Trd_Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2S struct {
	Header    *Trd_Common.TrdHeader `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	OrderType *int32                `protobuf:"varint,2,req,name=orderType" json:"orderType,omitempty"`
	Code      *string               `protobuf:"bytes,3,req,name=code" json:"code,omitempty"`
	Price     *float64              `protobuf:"fixed64,4,req,name=price" json:"price,omitempty"`
	OrderID   *uint64               `protobuf:"varint,5,opt,name=orderID" json:"orderID,omitempty"`
	// 为保证与下单的价格同步，也提供调整价格选项，以下2个为调整价格使用，对港、A股有意义，因为港股有价位，A股2位精度，美股可不传
	AdjustPrice          *bool    `protobuf:"varint,6,opt,name=adjustPrice" json:"adjustPrice,omitempty"`
	AdjustSideAndLimit   *float64 `protobuf:"fixed64,7,opt,name=adjustSideAndLimit" json:"adjustSideAndLimit,omitempty"`
	SecMarket            *int32   `protobuf:"varint,8,opt,name=secMarket" json:"secMarket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_GetMaxTrdQtys_28a5eba61e56a072, []int{0}
}
func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (dst *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(dst, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetHeader() *Trd_Common.TrdHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *C2S) GetOrderType() int32 {
	if m != nil && m.OrderType != nil {
		return *m.OrderType
	}
	return 0
}

func (m *C2S) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *C2S) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *C2S) GetOrderID() uint64 {
	if m != nil && m.OrderID != nil {
		return *m.OrderID
	}
	return 0
}

func (m *C2S) GetAdjustPrice() bool {
	if m != nil && m.AdjustPrice != nil {
		return *m.AdjustPrice
	}
	return false
}

func (m *C2S) GetAdjustSideAndLimit() float64 {
	if m != nil && m.AdjustSideAndLimit != nil {
		return *m.AdjustSideAndLimit
	}
	return 0
}

func (m *C2S) GetSecMarket() int32 {
	if m != nil && m.SecMarket != nil {
		return *m.SecMarket
	}
	return 0
}

type S2C struct {
	Header               *Trd_Common.TrdHeader  `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	MaxTrdQtys           *Trd_Common.MaxTrdQtys `protobuf:"bytes,2,opt,name=maxTrdQtys" json:"maxTrdQtys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_GetMaxTrdQtys_28a5eba61e56a072, []int{1}
}
func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (dst *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(dst, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetHeader() *Trd_Common.TrdHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *S2C) GetMaxTrdQtys() *Trd_Common.MaxTrdQtys {
	if m != nil {
		return m.MaxTrdQtys
	}
	return nil
}

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_GetMaxTrdQtys_28a5eba61e56a072, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_GetMaxTrdQtys_28a5eba61e56a072, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "Trd_GetMaxTrdQtys.C2S")
	proto.RegisterType((*S2C)(nil), "Trd_GetMaxTrdQtys.S2C")
	proto.RegisterType((*Request)(nil), "Trd_GetMaxTrdQtys.Request")
	proto.RegisterType((*Response)(nil), "Trd_GetMaxTrdQtys.Response")
}

func init() {
	proto.RegisterFile("Trd_GetMaxTrdQtys/Trd_GetMaxTrdQtys.proto", fileDescriptor_Trd_GetMaxTrdQtys_28a5eba61e56a072)
}

var fileDescriptor_Trd_GetMaxTrdQtys_28a5eba61e56a072 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x65, 0xf2, 0xd1, 0xb4, 0xb7, 0x2b, 0x47, 0x7d, 0x0c, 0x4f, 0x91, 0x21, 0xab, 0x71, 0xf1,
	0xfa, 0xca, 0x28, 0x2e, 0xdc, 0x49, 0x04, 0x15, 0x2c, 0xe8, 0x24, 0x7b, 0x09, 0x99, 0x8b, 0x46,
	0x4d, 0x13, 0x67, 0xa6, 0x60, 0xff, 0x40, 0x7f, 0xb7, 0x4c, 0x92, 0xb6, 0x29, 0x75, 0xf3, 0x56,
	0x9d, 0xf3, 0x45, 0x4f, 0xce, 0x85, 0x97, 0x85, 0xd1, 0xdf, 0x3e, 0xa0, 0xdb, 0x94, 0x7f, 0x0b,
	0xa3, 0xbf, 0xba, 0xbd, 0xbd, 0xbf, 0x62, 0x56, 0x9d, 0x69, 0x5d, 0x4b, 0x1f, 0x5d, 0x09, 0xb7,
	0x8f, 0xb3, 0xb6, 0x69, 0xda, 0xed, 0xfd, 0xf0, 0x33, 0xf8, 0x6e, 0x9f, 0x79, 0xdf, 0x28, 0x9c,
	0x9f, 0x83, 0x98, 0x1e, 0x02, 0x08, 0x33, 0x99, 0xd3, 0x3b, 0x98, 0xfd, 0xc0, 0x52, 0xa3, 0x61,
	0x84, 0x07, 0x62, 0x29, 0x9f, 0xae, 0x26, 0xd6, 0xc2, 0xe8, 0x8f, 0xbd, 0xa8, 0x46, 0x13, 0x7d,
	0x0e, 0x8b, 0xd6, 0x68, 0x34, 0xc5, 0xbe, 0x43, 0x16, 0xf0, 0x40, 0xc4, 0xea, 0x4c, 0x50, 0x0a,
	0x51, 0xd5, 0x6a, 0x64, 0x21, 0x0f, 0xc4, 0x42, 0xf5, 0x6f, 0xfa, 0x04, 0xe2, 0xce, 0xd4, 0x15,
	0xb2, 0x88, 0x07, 0x82, 0xa8, 0x01, 0x50, 0x06, 0x49, 0x1f, 0xfb, 0xf4, 0x9e, 0xc5, 0x9c, 0x88,
	0x48, 0x1d, 0x21, 0xe5, 0xb0, 0x2c, 0xf5, 0xcf, 0x9d, 0x75, 0x5f, 0xfa, 0xd4, 0x8c, 0x13, 0x31,
	0x57, 0x53, 0x8a, 0xae, 0x80, 0x0e, 0x30, 0xaf, 0x35, 0xbe, 0xdb, 0xea, 0xcf, 0x75, 0x53, 0x3b,
	0x96, 0x70, 0x22, 0x88, 0xfa, 0x8f, 0xe2, 0x3b, 0x5b, 0xac, 0x36, 0xa5, 0xf9, 0x85, 0x8e, 0xcd,
	0x39, 0xf1, 0x9d, 0x4f, 0x44, 0xfa, 0x1b, 0xc2, 0x5c, 0x66, 0x0f, 0xdd, 0xe1, 0x0d, 0x40, 0x73,
	0x9a, 0x9f, 0x05, 0x9c, 0x88, 0xa5, 0xbc, 0x99, 0x46, 0xce, 0xc7, 0x51, 0x13, 0x67, 0xfa, 0x0a,
	0x12, 0x85, 0x7f, 0x76, 0x68, 0x1d, 0x15, 0x10, 0x56, 0xd2, 0x8e, 0x7f, 0x37, 0x64, 0x2f, 0xaf,
	0x9d, 0xc9, 0x5c, 0x79, 0x4b, 0x7a, 0x20, 0x30, 0x57, 0x68, 0xbb, 0x76, 0x6b, 0x91, 0xbe, 0x80,
	0xc4, 0xa0, 0xeb, 0xf7, 0xf7, 0xd1, 0xf8, 0x6d, 0x74, 0xf7, 0x7a, 0xbd, 0x56, 0x47, 0x92, 0xde,
	0xc0, 0xcc, 0xa0, 0xdb, 0xd8, 0xef, 0x7d, 0xab, 0x85, 0x1a, 0x91, 0x5f, 0x1c, 0x8d, 0xc9, 0x86,
	0xf3, 0xf8, 0x0d, 0x8e, 0xd0, 0x17, 0xb1, 0xb2, 0x62, 0xd1, 0xe4, 0x23, 0x2e, 0x8b, 0xe4, 0x32,
	0x53, 0xde, 0xf2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x39, 0x71, 0xaf, 0xa5, 0x02, 0x00, 0x00,
}
